# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9d853c9f5467cd6c742e0ecb3227e0003aac0f140cacb81284e2f421f80094ef34f981301ef5e3a6f4cf0dfc9afce9f957575cf4d5e2fdd9365186ad98d1559a

test:
  secret_key_base: 6b77c3865dbe2c9c61f4a2d8e374b5b0e468c64c1168b380ff896ed12fb06609928ce3e25eb35887ac5cfb422ac2c1d9fda1b6c958b5209a03149f4c05ee8820

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
